language: go
sudo: required

services:
  - docker
 
before_install:
  - docker build -t feiren-v2ray/web .
  - docker login -u "$HEROKU_EMAIL" -p "$HEROKU_APIKEY"
  - docker push "$HEROKU_APPNAME"/web
